### ISSUE TITLE
gatk.bam error 256

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#91]
HI again! So the program was running fine for me till it got to the gatk.bam step and errored with the following error. I've never seen it before and no idea what it means! Any ideas? Do I need to downgrade my java?

Cheers!

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by cutpatel** [comment]
Hi,

picard decided to switch to JAVA 17 in their version 3. We need to adjust the bioconda recipe.

EDIT: Only do the install command to downgrade the version. The remove command will also deinstall other packages.
_For a quick fix you can remove picard from the activated mtbseq environment:
`conda remove picard`_

And then install a specific version of it:
`conda install picard=2.27.5`

**Comment by peflanag** [comment]
Amazing thanks! I will try that now!

**Comment by peflanag** [comment]
So after doing that in the mtbseq env, the mtbseq command is no longer found?


(base) drflanman@Peters-MacBook-Air-4 ~ % cd /Users/drflanman/Documents/Work/HSE/Research/Connolly_OB/MTBseq
(base) drflanman@Peters-MacBook-Air-4 MTBseq % conda activate mtbseq
(mtbseq) drflanman@Peters-MacBook-Air-4 MTBseq % mtbseq --step TBrefine --ref 22S3269 --distance 5 --threads 8
zsh: command not found: mtbseq
(mtbseq) drflanman@Peters-MacBook-Air-4 MTBseq %

**Comment by cutpatel** [comment]
The command is MTBseq ; ).

I have updated the bioconda recipe and also bumped the version to 1.1.0, need to wait until the pull request is merged.

**Comment by peflanag** [comment]
I tried both MTBseq and mtbseq and neither worked?

![image](https://github.com/ngs-fzb/MTBseq_source/assets/32863969/4916b942-f6f0-4a93-b265-361c724c3af6)

**Comment by peflanag** [comment]
I’ll wait for the recipe in conda to update and I’ll delete and reinstall the env!

**Comment by cutpatel** [comment]
You could check with `conda list` which tools and their versions are installed in the current environment.

**Comment by cutpatel** [comment]
Hey, sorry, it seems when you removed the picard package it actually removed everything.

You only need to do `conda install picard=2.27.5` to downgrade picard. 

So reinstall mtbseq and then downgrade picard.

**Comment by peflanag** [comment]
So I just did that and the image is below. Since I don't see mtbseq does that mean when I removed Picard it removed mtbseq too? Or would you not expect to see mtbsew in the Conda list in the env?

<img width="579" alt="Screenshot 2023-08-23 at 14 59 55" src="https://github.com/ngs-fzb/MTBseq_source/assets/32863969/f3d1a3e3-25ef-4721-ba41-80a254da6aee">

**Comment by peflanag** [comment]
Actually going into the file path where my Conda envs are there MTBseq is no longer there! I'll reinstall and remove Picard again?

**Comment by cutpatel** [comment]
> Hey, sorry, it seems when you removed the picard package it actually removed everything.
> 
> You only need to do `conda install picard=2.27.5` to downgrade picard.
> 
> So reinstall mtbseq and then downgrade picard.

Please see my earlier comment!

**Comment by peflanag** [comment]
sorry I missed that comment! I'll reinstall now!
